### PR TITLE
Prevent lint races in lint_view

### PR DESCRIPTION
**Pull request by FichteFoll**
I was running into an issue where I had `yamllint` executed up to 15 times for a single file for no apparent reason. I could re-lint only the affected file (`ctrl+k, l`) and would receive a variable amounts of errors for the same lines. In the console, I could confirm that the linter was indeed run multiple times and all the results were combined. This hints at a race condition.

Then I realized I had this "fix" up in my stashes, which I made when I noticed the usage of `lambda` in this situation, which I know from PackageDev can turn out detrimental. Turns out that this seems to fix the described problem, as I'm unable to reproduce it anymore after mutliple attempts.

See commit message for a technical explanation.

### CODE REVIEW

**Comment by kaste** [comment]
Isn't this the correct test

```
    run = run_concurrently(max_workers=5)
    test = run(
        lambda: print('**', i)
        for i in range(5))
    list(test)
```

**Comment by FichteFoll** [comment]
You need more items than workers to trigger the race.

```py
from concurrent.futures import ThreadPoolExecutor, as_completed, wait


def run_concurrently(tasks, max_workers=5):
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        work = [executor.submit(task) for task in tasks]
        yield from await_futures(work)


def await_futures(fs, ordered=False):
    if ordered:
        done, _ = wait(fs)
    else:
        done = as_completed(fs)

    for future in done:
        try:
            yield future.result()
        except Exception:
            import traceback
            traceback.print_exc()


results = run_concurrently(
    lambda: print('**', i)
    for i in range(15)
)
list(results)
```

```
** 0
** 1
** 2
** 3
** 4
** 14
** 14
** 14
** 14
** 14
** 14
** 14
** 14
** 14
** 14
```

**Comment by kaste** [comment]
Yeah, okay, I'm interested in the fix, not in the stylistic stuff.

**Comment by kaste** [comment]
Okay, I changed my mind while thinking about #792. I need `run_concurrently` anyway as one function, not as a factory.

All or nothing. 👍

**Comment by braver** [comment]
✨

**Pull request merged**
