### PR TITLE
Return early if `context_sensitive_executable_path` returns (True, None)

### LINKED ISSUE #987: TypeError: can only assign an iterable
Linting triggers automatically, and I get this output in the console:
```
SublimeLinter: ERROR:

 Lint task failed.
Traceback (most recent call last):
  File "lint.backend in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 201, in await_futures
  File "./python3.3/concurrent/futures/_base.py", line 394, in result
  File "./python3.3/concurrent/futures/_base.py", line 353, in __get_result
  File "./python3.3/concurrent/futures/thread.py", line 54, in run
  File "lint.backend in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 96, in execute_lint_task
  File "lint.linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 908, in lint
  File "lint.linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 631, in get_cmd
  File "lint.linter in /home/mandx/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 667, in build_cmd
TypeError: can only assign an iterable
```

### PR DESCRIPTION
**Pull request by kaste**
Fixes #987

### CODE REVIEW

**Comment by braver** [comment]
I can't easily match the setup of the original issue and not sure I fully catch what's going on there. I's prefer not to have to dig into that right now. This doesn't look terrible, so merge at will.

**Comment by kaste** [comment]
@braver I can't close issues in our `eslint` repo

**Comment by braver** [comment]
@kaste how about now?

**Comment by kaste** [comment]
Works, ty.

**Comment by STRML** [comment]
Will there be a release soon for this? Otherwise it is a very annoying experience with this error pane popping up.

**Comment by kaste** [comment]
@STRML Okay released.

**Pull request merged**
