### PR TITLE
expose ERROR and WARNING via init

### LINKED ISSUE #915: Highlights refactoring broke "highlight.ERROR/WARNING"
[This refactoring](https://github.com/SublimeLinter/SublimeLinter/commit/f3a57dc) of the `highlight` module broken the [SublimeLinter-annotations](https://github.com/SublimeLinter/SublimeLinter-annotations) linter. I was going to send a pull-request to the other repository but figured it's better to report the issue here since the code is still under development _(for version 4.0.0)_.

```
reloading plugin SublimeLinter-annotations.linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/root/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-annotations/linter.py", line 15, in <module>
    from SublimeLinter.lint import highlight, Linter
ImportError: cannot import name highlight
```

### PR DESCRIPTION
**Pull request by braver**
@kaste and @FichteFoll to replace #921 and then fix the plugins.

-----
fix #915

### CODE REVIEW

**Comment by braver** [comment]
Or do they go in `lint/__init__.py`? @kaste?

**Comment by braver** [comment]
Care to elaborate?

**Comment by FichteFoll** [comment]
For the record, I still meant to keep the definitions in the const module but import and expose them from init.

I can also see arguments against this ("this" being exposing stuff in the main package over having plugins import from const) , but overall I'm positive on that regard. Would like to wear @kaste's take as well, though.

**Comment by braver** [comment]
I think it’s really hard to pin down what plugins can and cannot import. I also don’t have enough python experience to say where stuff should go and made a guess here based on your comments. 

But if they’re set in const, there is nothing stopping plugins from importing them from const right? Except perhaps conventions (I wouldn’t know) or perhaps documentation (if someone reads it).

**Comment by FichteFoll** [comment]
They *can* import everything, but they can only rely on what's documented. If the attributes are documented to be in the main package module, then plugins may only use that. Anything else is open for breakage at any time.

**Comment by braver** [comment]
Ok, then we just need to decide what’s the cleanest way to expose this. I think via const makes a lot of sense, and doesn’t duplicate anything on our end?

**Comment by braver** [comment]
Yeah, this PR is crap. Let's talk in the issue at #915

**Pull request closed without merging**
