### PR TITLE
Expand info about overriding selector for given linter.

### LINKED ISSUE #1177: Question: how to activate explicitly multiple linters for given file types?
Let say I have ansible files, which are plain .yml files.
How can I add ansible-lint and yaml-lint to such files explicitly?

From what I see the only plugin that activates itself is 'annotations'...

### PR DESCRIPTION
**Pull request by nvtkaszpir**
Fixes #1177

### CODE REVIEW

**Comment by kaste** [comment]
That's a super nice contribution. 

I don't know if you need PackageDev honestly, I thought this is ScopeHunter. Lol.

**Comment by nvtkaszpir** [comment]
Hm actually now I'm not sure how I managed to get that menu option....
Updated PR.

**Comment by kaste** [comment]
I remember braver said this is built-in. 😁

**Comment by braver** [comment]
Show Scope Name is built in. You can’t make color shemes without it.

**Comment by braver** [comment]
@nvtkaszpir I totally appreciate you putting effort into the docs here. I have some minor nitpicking here wrt the writing style (and I really think we should adhere to the one true brace style). Want me to provide feedback, or should I just merge and edit afterwards?

**Comment by nvtkaszpir** [comment]
Whatever you prefer.
I added the braces to avoid issues with sphinx shouting errors, so it's merely issue with whe way we use sphinx directives.

If we do not want to have a syntax highlight there then maybe use `text` - but also loose formatting.
Otherwise I suggest sticking to proper syntax with braces. We assume project users are advanced enough to edit json files ;-)

**Comment by braver** [comment]
Ok, cool. I need to write some docs myself later, so I’ll edit then. Thanks!

**Pull request merged**
