### PR TITLE
Better excludes

### LINKED ISSUE #1158: Better `excludes` patterns
Today I wanted to do something like this. 

```
		"excludes": [
             "*/node_modules/*",
             "!${folder}*",
			 "<untitled>"
         ]
```

This is not supported by our poor 😥 `fnmatch` from python std library but would be trivial to add.

We could also support a special `'<untitled>'`.

The above should then be read as, do only lint files from my current project, exclude new/untitled buffers and files from 'node_modules'.

### PR DESCRIPTION
**Pull request by kaste**
Fixes #1158 

This is somewhat naive, but maybe good enough (KISS, YAGNI you name it)

### CODE REVIEW

**Comment by kaste** [comment]
Works for something like 

image

Or the example in the original issue.

**Comment by braver** [comment]
Fancy! 🎉

**Comment by braver** [comment]
Works! 🛥 it!

**Comment by FichteFoll** [comment]
Docs?

**Comment by braver** [comment]
I updated the docs

**Pull request merged**
