### PR TITLE
For compatibility export a pseudo `highlight` from `lint`

### LINKED ISSUE #915: Highlights refactoring broke "highlight.ERROR/WARNING"
[This refactoring](https://github.com/SublimeLinter/SublimeLinter/commit/f3a57dc) of the `highlight` module broken the [SublimeLinter-annotations](https://github.com/SublimeLinter/SublimeLinter-annotations) linter. I was going to send a pull-request to the other repository but figured it's better to report the issue here since the code is still under development _(for version 4.0.0)_.

```
reloading plugin SublimeLinter-annotations.linter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/root/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-annotations/linter.py", line 15, in <module>
    from SublimeLinter.lint import highlight, Linter
ImportError: cannot import name highlight
```

### PR DESCRIPTION
**Pull request by kaste**
Fixes #915

### CODE REVIEW

**Comment by braver** [comment]
Don’t want to fix this on the receiving end? I think this is a bit ugly.

**Comment by FichteFoll** [comment]
Fixing on the receiving end isn't bad but it takes time. The current situation is that many linters were broken by the change.

**Comment by braver** [comment]
Well, there are only a few outside our/my management. The linters that are somewhat actively maintained have been been able to push releases within a day before. I don't mind going around to open PR's later today.

**Comment by kaste** [comment]
IMHO we stay backwards compatible if feasible. Is https://github.com/SublimeLinter/SublimeLinter/issues/915#issuecomment-362200920 up-to-date?

Note that we usually package an `__init__.py` so that users just import everything from there. So importing `util.X` and `const.Y` for stuff a lot of people need, is already not nice. If they import ERROR from *SublimeLinter* or *lint* we can refactor our code however we want. We just have to make sure our public API stays. E.g.

```
try:
	import VERSION from SublimeLinter
except ImportError:
	VERSION = 3
```

is the typical pattern in python. Likewise:

```
try:
	import PythonLinter from SublimeLinter
except ImportError:
	import PythonLinter from SublimeLinter.lint
```

**Comment by braver** [comment]
I agree on trying to stay compatible. However, the surface area is really big and fuzzy. As you say, the way some stuff was exposed is not very nice. This particular one was documented, but SL3 has such a rediculous amount of super verbose documentation I don’t know what else we’re exposing. So, if we break something, let’s fix it.

I think this PR is very ugly. If this is what we need for compatibility I would rather go out there and fix 10 plugins.

The list at #915 is up to date, I haven’t had time. Only did annotations to confirm a fix. I’ll go and make fixes everywhere after dinner if we don’t merge this PR. If you want to expose ERROR and WARNING via something else than const, that’s totally cool and I’ll wait for that.

**Comment by FichteFoll** [comment]
I would actually export them in init, I guess. This is quite important api, although not frequently used.

**Comment by braver** [comment]
Well that’s better all around than hacking it back into highlight then isn’t it?

**Comment by braver** [comment]
Let’s just merge this, release, and then break it again later to do it right.

**Pull request merged**
