### PR TITLE
Translate columns when linting using selectors

### LINKED ISSUE #767: Wrong column number on first line of selector based lintings
As you can see, a col offset must be applied to the first line.

image

I actually got this bug from code reviewing, and I have a fix.

### PR DESCRIPTION
**Pull request by kaste**
Fixes #767

This is really similiar to how `highlight.full_line()` works.

### CODE REVIEW

**Comment by kaste** [comment]
image

**Comment by kaste** [comment]
This code needs to be refactored, but first we need to fix bugs.

**Comment by kaste** [comment]
I meant: Please merge this, so I have a good `next` branch for the refactoring.

**Comment by braver** [comment]
All your open PR's have been merged, so go ahead.

**Pull request merged**
