### PR TITLE
Show active linters in the status bar

### LINKED ISSUE #1205: Show assigned linters in the status bar per view

### PR DESCRIPTION
**Pull request by kaste**
Fixes #1205

### CODE REVIEW

**Comment by braver** [comment]
If I disable and then re-enable a linter, it doesn't come back in the status bar. Tested using an html file with embedded styles and js, running the styelint, tidy and eslint linters and then disabling eslint temporarily. Eslint does run and highlight errors when it has been re-enabled, but isn't listed in the status bar anymore.

Also, this needs to be behind a setting.

Otherwise: 🌶 Never thought I'd find this useful but it's a really nice reminder of what's running actually. Just need more space in my status bar. Or a bigger screen. Or smaller pixels + better eyes.

**Comment by kaste** [comment]
That's how it is if you code with your kids 😵🤗

**Comment by braver** [comment]
I code with my 🐈 , does that count?

**Comment by kaste** [comment]
Only Garfield like 🐈 

I had to rewrite the assign linters to view code. Also how we get the linter settings. 

An open question is what exactly an 'active' linter is. E.g. I currently have the 'php' linter installed without actually having any 'php' on my computer. So the process is SL assigns 'php' to any 'html' file and 'deactivates' it (silently fails) bc no executable can be found. Net result: it will not show up in the status bar. Probably fine. 

It could also tell you of course: Hey you're running the 'php' linter all the time. What a waste. You should disable it. So, maybe it would be better when 'php' would actually show up as active linter.

**Comment by braver** [comment]
Hmmmmmmmm 🤔 

I think I would like it to display all linters that are active, not just assigned. If I expect php to be active, but it isn't for some reason, I'd want to debug that. Ie. if a linter is listed in the status bar I expect it to be able to detect errors.

**Comment by kaste** [comment]
Closing in favor of #1283

**Pull request closed without merging**
