### PR TITLE
Fix missing comma in Linux/Windows keymap files

### PR DESCRIPTION
**Pull request by mandx**

### CODE REVIEW

**Comment by mandx** [comment]
Checking JSON syntax seems like a candidate for a new CI validation step :)

**Comment by braver** [comment]
Oh crap, that’s a stupid mistake. Thanks for fixing!

**Comment by FichteFoll** [comment]
The package reviewer utility can be used for CI checking: https://github.com/packagecontrol/st_package_reviewer

**Comment by braver** [comment]
That looks super useful!

**Pull request merged**
