### PR TITLE
Iterate panel again

### LINKED ISSUE #1415: output panel only for current view
The output panel lists all result for all files in the current window. It would be nice if you could have a panel with just the errors for the current file. 

I imagine this would be setting:

```
"show all errors per": "window" | "view"
```

### LINKED ISSUE #1582: In the panel show 'affected' files nearby active file
Usual sort order for the files in the panel is `a, b, c, d` (surprise!). 

In #1556 we focus the active view, and for that, say `b` is active, we re-sort to `a, c, d, b`. 

Since we have now multi-file linters, we should group 'related/affected' files. This information is stored in `affected_filenames_per_bid`. Say linting b produced results for files `b, x, a`, we should re-sort to `c, d, b, a, x`. 

Rationale: Typical, traditional linters report only per-file, and with #1556 we get a pretty clean picture. Type-checkers (ususally) can show results from dependent files and a user will likely see these results nearby. I think this could be a good default, automatic behavior.

### LINKED ISSUE #1679: Panel updates too often for multi-file reporters
In the performance PR #1673 I reverted https://github.com/SublimeLinter/SublimeLinter/commit/2cd32b7a6bc0d34b538aa8a71cd2930569da4c88 (and its successor https://github.com/SublimeLinter/SublimeLinter/commit/e803a44a38d70d7ac8581ff98f94858cd2df30d4) bc they looked complicated and unnecessary.  But we forgot that these commits weren't sole performance optimizations but visual optimizations.  Now, without them the panel (can) again look like this:

aBj98NYsQl

Basically, it looks like the errors streaming in and we just have too many updates which is totally ugly and not *just too slow*. 😞  

I mark as bug because it is really a visual bug.

### PR DESCRIPTION
**Pull request by kaste**
Fixes #1415 
Fixes #1582 
Fixes #1679 

So again the panel gets some more ❤️, and it's awesome.

1. As shown in the video in #1679 we needed a "throttler". 
2. Finally rebased #1556 
3. Simplified hack to hold the viewport stable.

### CODE REVIEW

**Comment by braver** [comment]
Oh, I need to set aside some time to play with this. Sounds good!

**Comment by kaste** [comment]
Hope 🤞 this works because it's super awesome. That's the one PR **I** wanted for 6 months.

**Comment by braver** [comment]
This is 🔥🔥

I wanna try if I can throw some more complicated scenarios at it, but some first tests are really positive.

**Comment by braver** [comment]
If had to nitpick anything here, it's that now it's really nice to keep the panel open all the time, but sometimes I have a slow linter and when I open a file it will say "no lint results" until the linter is done. It's too easy to interpret this as "all green", instead of "results inconclusive, come back later". 

Functionally though, it feels rock solid and smooth to me.

**Comment by kaste** [comment]
Yeah, if you make a good UI change, and especially something instant without flicker, new enhancement requests arise immediately.

**Comment by kaste** [comment]
(Have you tried: Make the panel bigger; make the whole window smaller. The filename stays. 😲)

**Comment by braver** [comment]
> make the whole window smaller. The filename stays

wut 😱

**Pull request merged**
