### PR TITLE
WIP: Show a link in the tooltip if url is given

### PR DESCRIPTION
**Pull request by kaste**
Related #1463 

We can afaik only show text links in Sublime. So we have unicode points or ... well text. @braver for the design.

Bc we don't have linters which provide a url right now, we construct a google search for testing.

### CODE REVIEW

**Comment by braver** [comment]
Can we simply make the linter name and error code clickable (and make it look like a link, i.e. `bluish` and underlined?

**Comment by kaste** [comment]
The links are blueish by default or with my color scheme at least.

**Comment by kaste** [comment]
Some pics:

image

image

image

image

image

image

image

**Comment by braver** [comment]
So, assuming linters that provide URL’s also have error codes (because what would you link to otherwise), the first image looks best to me. In the context of a website I would remove the underline, but here it’s needed because ST highlights things in blue that aren’t links and it should be really obvious you can click on them. I personally don’t feel like adding icons or anything.

**Pull request closed without merging**
