### PR TITLE
Refactor around `update_buffer_errors`

### PR DESCRIPTION
**Pull request by kaste**
- Change signature or `update_buffer_errors` 

```diff
-def update_buffer_errors(bid, view_has_changed, linter, errors):
-    # type: (Bid, ViewChangedFn, Linter, List[LintError]) -> None
+def update_buffer_errors(bid, linter, errors):
+    # type: (Bid, LinterName, List[LintError]) -> None
```

- Factor `def _assign_linters_to_view(view, next_linters):`

### CODE REVIEW

**Comment by kaste** [comment]
This is actually good to read, we still need a bit more to get the repo in a clean state again.

**Comment by kaste** [comment]
If possible, review this one first bc I need to put commits on top of it.

**Comment by kaste** [comment]
@braver Hi! 😉

**Comment by braver** [comment]
I don't see any problems with a mix of linters, views, windows, different lint modes, etc. Anything I should test for specifically?

**Comment by kaste** [comment]
No, this is an internal refactoring. I had this one running for the last  month or so.

**Comment by braver** [comment]
Ok, let’s ship it then 👍🏻🚤

**Comment by braver** [comment]
🚀

**Pull request merged**
