### PR TITLE
fix line report

### PR DESCRIPTION
**Pull request by braver**
Calling the line report command only displays the error at your cursor. This is incorrect behaviour. This PR changes that:

- show line report when cursor not at error
- don't filter errors for cursor position when requesting line report
- line report really is just the gutter report but not at the gutter

### CODE REVIEW

**Comment by braver** [comment]
Thanks, that's a good point. There is actually no need to set the col to 0 if someone hovers over the gutter, and if the line report is called manually it makes more sense to show it at the cursor. In fact, it wouldn't show if you've scrolled horizontally. So this fixes that too by being less smart.

**Comment by kaste** [comment]
LGTM 🚢

**Comment by FichteFoll** [comment]
Uh, mind explaining again why the column shouldn't be zero for the on_hover gutter popup?

**Comment by braver** [comment]
It already is zero and doesn’t have to be set like that. As far as my tests reveal anyway.

**Comment by FichteFoll** [comment]
Ah okay, I see the point kwarg now. Can't check the full diff on mobile.

**Pull request merged**
