### PR TITLE
Do not 'hit' the active_view twice at startup

### PR DESCRIPTION
**Pull request by kaste**
Sorry, you merged too fast.

### CODE REVIEW

**Comment by braver** [comment]
Ohoh, now everyone knows I don’t review and test everything...

**Comment by kaste** [comment]
Still not working as expected. I 'hit' the active view before the other views, which will `queue.put()`. Still, the active view will be linted last. Or second at least, I only test with two view_groups. But a python Queue is FIFO, isn't it?

**Comment by braver** [comment]
My cat is currently preventing me from getting out my chair, but I’ll have a look later. I didn’t notice anything weird in your previous PR though.

**Comment by kaste** [comment]
Okay, got it. Our internal code runs tasks added to the queue within the same tick in random order.

**Comment by braver** [comment]
Ah. I just confirmed the behaviour here. I don't think it's much of a problem really.

**Pull request merged**
