### PR TITLE
Fix and refactor code using our first unit tests

### LINKED ISSUE #1514: Run tests automatically against master and PRs
Ideally we use a different service for the tests so that Travis and the "other thing" can run in parallel. 

Multi-Platform is not important bc we currently don't have tests that should behave differently here.

### PR DESCRIPTION
**Pull request by kaste**
Closes #1514

### CODE REVIEW

**Comment by kaste** [comment]
Where does this comment from @codecov-io come from? I don't see this in integrations/services blah panel in Github. Can this be turned off? (A *small* note would be okay, but this is ridiculous.)

**Comment by kaste** [comment]
LGTM actually.

**Comment by braver** [comment]
I need to work some [bugs](https://en.wikipedia.org/wiki/Common_cold#Viruses) out of my system, but I promise to make some time very soon to look at this properly. Hope to be up and running again next week. 🤞

**Comment by kaste** [comment]
🍷 + 💊 => 🛌 💤 ⭐️   💃

**Comment by braver** [comment]
I'm back! ;) 

Looks good 👍

**Comment by kaste** [comment]
Hooray

**Pull request merged**
