### PR TITLE
First working version of panel multiselect.

### PR DESCRIPTION
**Pull request by pykong**
If multiple error regions belong to the current position they will all get highlighted within the panel.
Addresses: #803 #804

### CODE REVIEW

**Comment by pykong** [comment]
multi_line_select

Our panel gets more amazing by the day!

Multiselect has arrived. It runs very smooth already. Still, report any trip ups here, so I can fix 'em.

I opened the PR into the (as of now unmerged) branch it is derived from and depends on. I hope this was the right approach here git-wise.

**Comment by braver** [comment]
You can set the PR to merge into master. That way we can merge this after the branch it depends on. All PR’s should merge into master, if we should do one before the other you can indicate that in a comment (as you did).

**Comment by FichteFoll** [comment]
It would make the PRs harder to review though, since they contain more changes. You could for example just change the target branch once the dependant PR has been merged.

**Comment by braver** [comment]
Git is nothing if not rich in options ☺️

**Comment by pykong** [comment]
Yeah, git is a hundred-headed hydra. 
I have already switched target branch to master this morning.
What do we do?

**Comment by braver** [comment]
Let's just focus on panel_region_sort and it'll sort itself out later

**Comment by pykong** [comment]
Code will be superseded by #823

**Pull request closed without merging**
