### PR TITLE
Panel: Implement blacklisting.

### PR DESCRIPTION
**Pull request by pykong**
Addresses: #710 

**NOTE:** #752 should be merged before this.

### CODE REVIEW

**Comment by braver** [comment]
I notice that you may filter it so that no errors remain in the panel. However, a file *is* listed if it has errors, regardless of filtering. This is of course also an issue with the existing whitelist. Think we might be able to put a message in there, e.g. "No errors due to filtering"?

**Comment by FichteFoll** [comment]
I would just filter the file as well.

**Comment by braver** [comment]
Yes, that would also be good :)

**Comment by pykong** [comment]
The best way to implement the change requested requires the `RenderLines` class from the branch `panel_select`. What is the best way to fare, *git* wise here?

**Comment by braver** [comment]
Well, because it's git there are at least 3000 ways to do it, but I'm fine if you just merge the two branches and present a single PR for both features.

**Comment by FichteFoll** [comment]
I would try to get `panel_select` merged first. In the meantime, you can start implementing this on a separate branch starting from panel_select and then rebase from `master` once that is merged (and submit a PR).

**Comment by pykong** [comment]
Closed. Changeset migrated to #798

**Pull request closed without merging**
