### PR TITLE
Add sphinx-build linkcheck to travis, speed up builds

### PR DESCRIPTION
**Pull request by nvtkaszpir**
I'm a bit mental about docs recently...

### CODE REVIEW

**Comment by braver** [comment]
I usually read the travis.yml for how-to (ie. what to install and what commands to run). Perhaps add some comments there about what happens (e.g. the html you can read locally is in the docs-out folder) and how to review your edits that way?

**Comment by nvtkaszpir** [comment]
As @braver said, read .travis.yml.
Actually  I was thinking about simple script (or makefile) with different targets, which could eventually replace travis `script:` lines and allow run multiple tests concurrently. But this requires further discussion.

For now I can add a new document to docs about how to develop the plugin using pyenv+virtualenv. You want it in this PR or a new one?

**Comment by kaste** [comment]
Nah, that's okay. I thought they ship an editor to use locally. (Auto-build, etc.)

**Comment by nvtkaszpir** [comment]
for auto builds you can try using https://pypi.python.org/pypi/sphinx-autobuild

**Comment by kaste** [comment]
Okay, thanks.

**Pull request merged**
