### PR TITLE
Export LintMatch

### LINKED ISSUE #1563: Expose 'LintMatch' as a toplevel export
We encourage users to use and return 'LintMatch' instances instead of 7-tuples so we need to proper export this class.

Consider though renaming it to 'LintError' first.

### PR DESCRIPTION
**Pull request by kaste**
Fixes #1563

### CODE REVIEW

**Comment by kaste** [comment]
🙄 I did not rename it

**Comment by kaste** [comment]
Ah well, `LintMatch` or `LintError` which can also be a warning or note. `LintError` is like we have the severity in the name. `LintMatch` is like it's only useful for regex matchers but actually it is extremely useful for JSON reporters. 🆘

**Comment by kaste** [comment]
In Atom it's called `Message`, and what we call 'message' they call 'description'. In VSCode it's a list of `Diagnostic` (items?) LOL.

**Comment by braver** [comment]
Cache invalidation, off by one and naming things...

**Comment by braver** [comment]
🚤 it because 🤷🏼‍♂️❓

**Comment by kaste** [comment]
Obviously, we go with `LintFact` :grin:

**Comment by braver** [comment]
Obviously! 

LintThing? LintReport?

**Comment by kaste** [comment]
`yield Fact`

**Comment by braver** [comment]
I like that actually

**Comment by braver** [comment]
It’s too nice really

**Pull request merged**
