### PR TITLE
Alt Zombies

### LINKED ISSUE #1315: Prevent dangles for highlights and icons
As seen https://github.com/SublimeLinter/SublimeLinter/pull/1306#issuecomment-380461021

highlight dangles can still be produced if regions magically appear on 'redo'.

Also: probably not all ways to modify the buffer are handled by invalidate errors *under cursor*.

### PR DESCRIPTION
**Pull request by kaste**
The lean thing:tm:

@braver's idea but without the file 🤣 

We use an everstore to store all region keys ever drawn by SL
per bid. On undo/redo we just restore the current state from
this everstore.

Fixes #1315

### CODE REVIEW

**Comment by braver** [comment]
I like this!

For the record, I never wanted to propose storing stuff elsewhere than in memory. If I did I blame auto correct and my iPad’s stupid keyboard. 😉😁

Do you have a preference between this and the Original™️ Zombie Protection?

**Comment by kaste** [comment]
I prefer this one of course bc I don't need to read 60 lines of comments to understand it.

**Comment by braver** [comment]
Want me to make some ascii art? Will make me feel like I’m really contributing too 👨🏼‍🎨

**Comment by kaste** [comment]
A Zombie in ~6 lines maybe here:

image

**Pull request merged**
