### PR TITLE
Add additional guard against `which is None`

### LINKED ISSUE #1207: ERROR: Linter crashed. TypeError: argument of type 'NoneType' is not iterable
GEtting this with Version 4.1
Sublime 3, running Windows 10.

traceback:
SublimeLinter.sublime-package", line 97, in execute_lint_task
SublimeLinter.sublime-package", line 754, in lint
SublimeLinter.sublime-package", line 475, in get_cmd

I'd also encourage folks to hop over and vote this issue up: https://github.com/wbond/package_control/issues/1349 (Add support for pinning / installing specific package versions, for cases where the latest is failing)

### PR DESCRIPTION
**Pull request by kaste**
Fixes #1207

### CODE REVIEW

**Comment by braver** [comment]
Shall we release this right away?

**Comment by kaste** [comment]
I have to go. Sorry. Already late.

**Comment by braver** [comment]
Ok, I confirmed the fix with SL-php.

**Comment by willrowe** [comment]
I can also confirm this fixes SublimeLinter-php.

**Comment by braver** [comment]
Thanks for checking!

**Pull request merged**
