### PR TITLE
Use shlex.split() variant for Windows support

### LINKED ISSUE #1442: `shlex.split` is not Windows safe
We use `shlex.split` for `cmd` and `args` if they're provided as strings. This works okay for simple stuff, but in the end it does not split confirming to Windows rules. (E.g. never split a Windows path with it bc it doesn't like `\`s.)

### PR DESCRIPTION
**Pull request by kaste**
Fixes #1442

### CODE REVIEW

**Comment by braver** [comment]
So, does this take into account things like wsl, mingw etc.? Other than that I'm not set up to test this.

**Comment by kaste** [comment]
Erm, no. It's about how we split cmd and args given as strings into lists.

So, if I messed this up, we can call the 🚑 bc they 🔫 me.

**Comment by braver** [comment]
Works for me!

**Comment by kaste** [comment]
Now, let's see if we have a working master.

**Comment by braver** [comment]
Looks ok for me

**Comment by kaste** [comment]
✌️

**Pull request merged**
