### PR TITLE
Only show "Quick Action" in the context menu if there is any available

### PR DESCRIPTION
**Pull request by kaste**
~~Unbelievable ugly.~~

~~I looked at greying this "Quick Action" entry.  This gets really ugly code-wise.  Basically, we compute the actions in `is_enabled` or `is_visible` and pass it around.  But fun facts and fun bugs.  The order Sublime calls `enabled` or `visible` changes, on right clicks for the context menu `enabled` is called twice and *before* `visible`. (That's a double foul, as far as I can see, if `visible` returns `False` the entry does not appear, and asking `enabled` was a wasted computation because it only greys otherwise *visible* entries. Calling it even twice doesn't help here.)~~

~~Naturally you'd want to cache this computation, I'll invalidate the cache here "time-based" on the exact next tick.  Throughout SL we only cache by memoization (lru_caches), I would have to think and play with it if hashing the `view.sel()` plus `view.change_count` plus the uids in the error store for the file would be a unique cache key to proper invalidate.~~

~~Let's just look at if "greying" is that great.~~

Trivially, we only add an entry to the context menu if there are any actions available.  We never grey out.

### CODE REVIEW

**Comment by braver** [comment]
Well, what is kind of inconsistent now is that Quick Actions is not there for some files, and there but greyed out in others. 

For main menu entries graying out is an important pattern. It ensures things are always in the same place, but can not necessarily always be used. 

For a context menu though, I already expect the menu to change based on what I right-clicked on (ie. the context). It's different all the time. It should only have things applicable to that context. Therefore, I don't think we should ever grey-out context menu entries. If it's not something you can use, don't show it.

**Comment by kaste** [comment]
I ♥️ you.  That will make the code easier and the ux better.

**Comment by braver** [comment]
Aww, I ❤️ you too man 🤣

**Comment by kaste** [comment]
Here as in #1756 the code gets easy as soon as we don't "grey" anything.  Implementing both `is_enabled` and `is_visible` makes everything ugly because Sublime calls these callbacks in any order and even multiple times.

**Comment by kaste** [comment]
Let's test this all together "in concerto".  Since we have it on "dev" we could even rebase "dev" if we see something so bad we feel a revert would be better than a fix.

**Pull request merged**
