### PR TITLE
improved error message shown to user.

### PR DESCRIPTION
**Pull request by ew4321**
The error message now gives a hint on how to solve the issue by directing them to the troubleshooting guide in SublimeLinter's docs and to the readme. #1418

### CODE REVIEW

**Comment by braver** [comment]
Thanks! Two things:

1. It needs a line break in there, because it comes out like so:
```
SublimeLinter: WARNING: markdownlint cannot locate 'markdownlint'Please refer to the readme of this plugin and our troubleshooting guide: http://www.sublimelinter.com/en/stable/troubleshooting.html```

2. The composer_linter and node_linter have similar messages and need an update there too. The file you modified is just the base linter, most plugins use a more specific version.

**Comment by ew4321** [comment]
Hi. I'm new to this sort of stuff, and I messed something up so I made the changes in a [new branch](https://github.com/SublimeLinter/SublimeLinter/pull/1502).

p.s. How can I simulate an error msg like you did above, so i can find my own mistakes next time?

**Comment by braver** [comment]
What I did was install a plugin of which I don't have the actual linter installed (like markdownlint) and then open a file it can lint (like a README).

**Comment by kaste** [comment]
Thank you.

Interesting duplication in composer and node_linter. We probably should just `return False, None` before trying to find the global cmd. Finding a global cmd is the default behavior of SublimeLinter anyway.

**Pull request closed without merging**
