### PR TITLE
Use thread_name for additional info in debug messages

### PR DESCRIPTION
**Pull request by kaste**
Code to explain #930 @FichteFoll

### CODE REVIEW

**Comment by FichteFoll** [comment]
I have a better idea. Just a moment.

**Comment by FichteFoll** [comment]
This is my proposal: https://github.com/FichteForks/SublimeLinter3/commit/afeffec32923641b8ebd1bcf360e4d972b9cb2eb

**Comment by FichteFoll** [comment]
Note that this assumes that `next(task_counter)` is thread-safe, which it is probably not, so I guess I need a mutex here.

**Comment by FichteFoll** [comment]
Actually, is `lint_view` ever called concurrently? Because the lint tasks are created in order (even through `run_concurrently`) on the thread that `lint` was called on and before the executor comes in.

**Comment by kaste** [comment]
It's basically concurrency hell here bc `queue.queue_lint` (or something similar named) already is on a separate thread. 😃

**Comment by FichteFoll** [comment]
I'll take that as a yes.

**Comment by kaste** [comment]
Btw your base backend.py is 2 iterations behind master.

**Comment by FichteFoll** [comment]
Yeah I need to merge master, but I'm not confident it would be pulled anyway so I'm not spending time on it until I get a positive sign on that.

**Pull request closed without merging**
