### PR TITLE
Prepare release message for 4.10.0

### PR DESCRIPTION
**Pull request by kaste**
Just start with compiling what changed.

### CODE REVIEW

**Comment by braver** [comment]
Good idea! LGTM 👍🏻🚀

**Comment by kaste** [comment]
We have a milestone 4.10.0 now bc there is a bug in master (#1564) (Of course, it's around an edge case, and probably nobody would ever notice 🤷‍♂️)

**Comment by braver** [comment]
👍

**Comment by kaste** [comment]
We must add 

- fixed #1565  
- added #1576

**Pull request merged**
