### PR TITLE
Keep error position in sync while editing

### PR DESCRIPTION
**Pull request by kaste**
Yes we can.

### CODE REVIEW

**Comment by kaste** [comment]
Oh, hi @braver 👋

**Comment by braver** [comment]
Hi 👋 

Those 4 commits work really well as far as I can tell (at least with that fix 😉 ). Wanna merge?

**Comment by kaste** [comment]
Hmmmm, that's a breakthrough PR no 🎉 no 🌶 ? Did you test this with lint_mode == save

**Comment by braver** [comment]
I tested with a file only linter and compared with the current state of master, and I must say it was day and night. However, I don’t like working on that TypeScript project no matter how good the linting is and that kinda limits my enthusiasm for the entire thing. With Python everything was already pretty awesome.

So, sorry. I do understand breakthrough here, so here’s some celebration for you:

🎉👌🏻🕺🏼🎆

**Comment by kaste** [comment]
So this PR is a bit tested and implements the feature. I'll merge without necessary refactoring. So they will be fixups and iterate-on PRs as soon as I get my head around how this now actually works.

**Comment by kaste** [comment]
Thanks for the 🕺

**Pull request merged**
