### PR TITLE
Enable reloader after install/upgrade

### PR DESCRIPTION
**Pull request by kaste**
I did test this with a local repository; FichteFoll explained this in the kill_switch thread.

### CODE REVIEW

**Comment by kaste** [comment]
BTW, @FichteFoll `file://...` did not work. I have to serve the files via localhost.

**Comment by braver** [comment]
Well, it’s worth a try at least 👍🏻

**Comment by kaste** [comment]
The actual zip packages must be served via localhost. The repository hack worked with the local file.

**Comment by kaste** [comment]
About the noise: My first issue here was in the range #6xx. This PR has the number #1372!

**Comment by kaste** [comment]
FWIW I made some notes https://github.com/SublimeLinter/SublimeLinter/wiki/Test-upgrade-locally

**Pull request merged**
