### PR TITLE
Two fixes for NodeLinter

### LINKED ISSUE #1118: NVM: cannot locate 'eslint' / 'node' etc
After recent update, Sublime always popup the tips:

`SublimeLinter: WARNING: eslint cannot locate 'eslint'`.

In detail:

I haven't install global eslint, because I have to extend the eslint rules in config file in projects, If using the global eslint, the `xxx-eslint-config` package is not used.

When the project is configed properly, and with local eslint installed, everything works very well.

But if I open a file not in project (in a single window), there always a popup tips in the sublime console.

In previous versions (not sure which version), no such problem.

### LINKED ISSUE #1188: NodeLinter `disable_if_not_dependency` doesn't work as intended

### PR DESCRIPTION
**Pull request by kaste**
Fixes #1118 
Fixes #1188

### CODE REVIEW

**Comment by kaste** [comment]
Better name for `disable_if_not_dependency`?

**Comment by braver** [comment]
This disables the linter if it’s not listed as a dependency in the package json, right? It’s not a terrible name. 🤷🏼‍♂️

**Comment by kaste** [comment]
Yeah, but we don't do that. We don't parse `package.json`. We search for `package.json` and take its folder as the project folder so we can peek at `node_modules/bin/linter_name`.

**Comment by kaste** [comment]
(`context_sensitive_executable_path` is also correct but why didn't they choose something like `which_executable`)

**Comment by braver** [comment]
Ah, that's a bit misleading then. `disable_if_not_installed`? `requires_installation`?

**Comment by braver** [comment]
I don't really care about the setting name, LGTM for me otherwise.

**Comment by Grantlyk** [comment]
Hey guys, when will this PR be released?

**Comment by braver** [comment]
@Grantlyk We're having some issues with the upgrade process itself, so we probably want to merge #1172 too to (hopefully) help in that regard.

**Comment by broonage** [comment]
Any update? My linter is all broken (been a couple of weeks since SublimeLinter was updated), just updated to 4.2.0, but no sign of this fix. :)

**Comment by braver** [comment]
The contents of this PR have been released. If you're having problems please open a new issue with some more info (debug logs) so we can figure out what's wrong with your setup.

**Comment by broonage** [comment]
Ok, sorry I didn't realise as I still get the same message and assumed it was not pushed. I will do, thanks.

**Comment by broonage** [comment]
I got it working, I had not realised the user settings had changed. thanks

**Comment by braver** [comment]
🎉

**Pull request merged**
