### PR TITLE
Fix: file regex of the panel view

### PR DESCRIPTION
**Pull request by kaste**
Since we auto-wrap long messages it is possible that any line can
end with a literal ':'.

https://regex101.com/r/Uzgmhh/1/

### CODE REVIEW

**Comment by kaste** [comment]
I had this bug last week and stashed this patch. @braver please take a triple look, we don't want to break the obvious.

**Comment by braver** [comment]
Won’t be in the same postal code of my laptop until later next week.

**Comment by kaste** [comment]
The fix of course doesn't work if we show absolute paths on Windows bc they contain a : after the drive letter. 🤔

**Comment by kaste** [comment]
Shit stash.

**Comment by braver** [comment]
Good catch, I wouldn't have gotten that just by staring at the regex. So you need to accept `^[A-D]:` or something.

**Comment by kaste** [comment]
Esp. A and B bc I always do my backups on floppies and sure stop on D. 😁

**Comment by braver** [comment]
Why did I type D and not Z? I don't know. Too many things going on today.
Of course, you're going to look on your DVD burner at D, but not on your netwerkshare that's going to be on M. 

I don't look back fondly on having to deal with this crap in Windows. It's affecting my ability to contribute to this issue :)

**Comment by kaste** [comment]
Then we go test driven

**Comment by kaste** [comment]
Hilarious, looks like `view.find_all_results()` returns pseudo linux paths on my Windows, but Windows paths on the travis linux. 🤣

**Comment by kaste** [comment]
Ok, green

**Comment by braver** [comment]
Excellent 🙆‍♂

**Pull request merged**
