### PR TITLE
Move common manifest-related features to a standalone mixin

### PR DESCRIPTION
**Pull request by AndrewMast**
This would enable us to create fancy errors for the failing of reading the manifest files (#1447). I plan on making those errors in this PR, but I just want to make sure I am going in the right direction.

Mind taking a look at this, @kaste or @braver?

(Edit: Also, kaste, you should join Sublime's discord server so we potentially don't have to spam people with notifications)

### CODE REVIEW

**Comment by kaste** [comment]
Hi again!

These base classes must be rewritten. For NodeLinter, we have some code here https://github.com/SublimeLinter/SublimeLinter-eslint/issues/270#issuecomment-470481041 and https://github.com/SublimeLinter/SublimeLinter-eslint/issues/270#issuecomment-471006154

We wouldn't go the mixin way, because plain functions give us better reusability and composability.

**Comment by AndrewMast** [comment]
So scrap the mixin idea? How would you propose to do it? All of the functions used in the NodeLinter and ComposerLinter were exactly the same except for the 'disable_if_not_dependency' in the NodeLinter...

**Comment by AndrewMast** [comment]
Should I make it just ManifestLinter and have Composer and Node extend it? It does the same purpose but I originally didn't do it because I didn't want people trying to extend the ManifestLinter....

**Comment by kaste** [comment]
I'm not prepared to answer this question right now. I'll come back tomorrow. (We usually also get bug reports tomorrow because we shipped 100+ commits just now.) 

I think there are probably more interesting things for you than copy/pasting my code from the comments I linked to above.

**Comment by AndrewMast** [comment]
I’ve decided to close this.

**Comment by kaste** [comment]
You can take a look at the new proposed NodeLinter in #1579. Sorry that I interrupted you here but I really had this worked out before in the eslint thread I linked above.

**Pull request closed without merging**
