### PR TITLE
Showcase: Flash jump position after goto command

### PR DESCRIPTION
**Pull request by kaste**
Flash error jumped to after invoking goto command. Flash scope is 'markup.bold', see in the code.

### CODE REVIEW

**Comment by braver** [comment]
They don't!

So, eh, we need to test the current state of master before releasing because we probably break a lot of people's computer if we don't right?

**Comment by braver** [comment]
Ok, clear. I'll look for bugs too. 👍 

This particular PR is for me a bit on the fancy side. It also overlays an outline highlight on my squiggly underlines and that looks a bit wonky. It's not bad, perhaps I need to get used to it.

**Comment by kaste** [comment]
We should manage somehow that something like this lands in master bc of the many PRs I never have the time to actually see it in action and improve it.

This PR here is merely an improvement for quiet views and otherwise invisible highlights. It also helps if you jump to an error currently not in the viewport. 

If it doesn't look good with squiggles I could hide them during flashing. But generally UI experiments are difficult if you cannot try them.

**Comment by FichteFoll** [comment]
Also note that some people still have pre-releases enabled and could help with testing such an unstable or develop branch.

**Comment by braver** [comment]
@kaste addon-i-fy this perhaps?

**Comment by kaste** [comment]
yep

**Comment by kaste** [comment]
This is now here https://github.com/kaste/SublimeLinter-addon-goto-flash

**Pull request closed without merging**
