### PR TITLE
Fix for ghost regions after undo

### PR DESCRIPTION
**Pull request by kaste**
Generally, Sublime keeps ghost regions of length 0 if you delete text
that has a region attached. Since we invalidate highlights under the
cursor when editing, we never see them, until the user hits 'undo'
then they re-appear (out of Sublime's internal cache).

This problem was hidden by the fact that we used generalized region keys
and so a following update always fixed the ghosts. But since we now use
uuid region keys, these ghost become permanent when SL forgets about
these keys and never redraws them.

Ideally we could redraw everything all the time, but here we store the
invalidated keys in memory and restore them on 'undo'.

### CODE REVIEW

**Comment by braver** [comment]
Ah, I noticed a dangling region but haven't found time to report it yet. So this would fix that? 🎉

**Comment by kaste** [comment]
🤞 or 🖕

**Comment by braver** [comment]
Yes, it's a shitty editor. It's also the best editor. Which probably says a lot about all the other editors.

**Comment by braver** [comment]
screen shot 2018-04-11 at 15 55 05

Ok, I can't seem to reproduce dangling inline highlights so easily anymore, but I managed to produce a dangling gutter mark.

**Comment by kaste** [comment]
Icon dangles should at least go away when you produce a new error with the same icon. The highlights here were complete, unreachable zombies.

**Pull request merged**
