### PR TITLE
Fix: Do not throw if there are no errors on a line

### LINKED ISSUE #1146: version 4.0.5 is broken when start
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 19
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 20
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 17
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 15
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 20
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 72, in on_selection_modified_async
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 84, in draw
  File "status_bar_view in /Users/jakit/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in messages_under_cursor
KeyError: 19

### PR DESCRIPTION
**Pull request by kaste**
Fixes #1146

### CODE REVIEW

**Comment by braver** [comment]
I don't know how to recreate the problem really, but some defensiveness here can't hurt.

**Comment by kaste** [comment]
Reject. `errors` here should be already a defaultdict (so it is defensive).

**Comment by braver** [comment]
See? I'm a useless reviewer 😞

**Comment by kaste** [comment]
Actually your comment brought me to this, so that's not really useless.

You can't reproduce the state bc it is a broken state. You cannot sanely get to this state.

Maybe @FichteFoll 

`error_per_line` is only initially a `dict` (so that it can throw `KeyError`). After `on_activate` or `lint_result` it becomes a `defaultdict` which is protected. Sublime calls `on_activate` right after `plugin_loaded`. That means `draw` gets called with an invalid initial state via `on_selection_modified` after module import but before `plugin_loaded`.

How is that possible?

**Comment by FichteFoll** [comment]
Unfortunately, ST does not guarantee that `plugin_loaded` is called before any event handlers. https://github.com/SublimeTextIssues/Core/issues/1508

**Comment by kaste** [comment]
Yes, sure it is this. I thought they just run `sublime_plugin.reload_plugin` 😕

**Comment by kaste** [comment]
Unfortunately, `plugin_loaded` must have been called before otherwise `active_view` would still be `None`. So that means `plugin_loaded` has been called, but not `on_activated`, instead `on_selection_modified`. I thought they call `on_activated` after `plugin_loaded` bc that's what they do in `reload_plugin`. 

@FichteFoll again

**Comment by FichteFoll** [comment]
So the issue is that on_sel_modified is called before on_activated? Are any of these async?

**Comment by kaste** [comment]
We exclusively use the async variants.

**Comment by FichteFoll** [comment]
The async variant is not called in reload_plugin iirc.

**Comment by kaste** [comment]
🤢

**Pull request merged**
