### PR TITLE
Showcase: Focus current file in panel

### PR DESCRIPTION
**Pull request by kaste**
As discussed in #1544. Solves #1415. Obviously on top of #1544.

### CODE REVIEW

**Comment by kaste** [comment]
Well, of course I don't add any setting here. You just switch branches 🙄

**Comment by kaste** [comment]
So take a look at this one @braver. This is still an implementation idea, not even 20 lines of code(!). 

Here we want that the user has clear focus on the current file, and not the other errors. See #1415. Due to the new scroller/viewport stuff in master this is unbelievable fast, yankfree. I mean you ctrl-tab the views, and the panel just updates basically instantly, no scrolling, no animations, no flicker. It is 🤹‍♀️ LOL

What I actually like here, and what is maybe a bit surprising when you only read #1415, is that it only *visually* focuses the current file, t.i. it actually does *NOT* hide the other files. E.g. it does not pretend I have a clean repo, and I can scroll up to see those if I ever want to without flipping flags. It is really just a visual trick, e.g. the panel looks empty/clean for clean files which is 👍 

(Disclaimer: I never had this branch running bc we just merged the other PR's I had the wrap-message PR checked out to see if it has bugs or is otherwise annoying.)

**Comment by braver** [comment]
Coolio! I definitely got some use out of the panel @ master today  and it was really solid. Will check this out next. 🎉

**Comment by braver** [comment]
Woo, this is rly nice m8.

**Comment by kaste** [comment]
Follow up in #1681

**Pull request closed without merging**
