### PR TITLE
Autonomous, self-contained panel

### LINKED ISSUE #827: [beta] AttributeError: 'module' object has no attribute 'update_panel_selection'
I am repeatedly getting this error in the sublime text console:

`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 538, in on_activated_async
    callback.on_activated_async(v)
  File "status_bar_view in /Users/nickmuoh/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 50, in on_activated_async
AttributeError: 'module' object has no attribute 'update_panel_selection'`

I am using sublimelinter v4.0.0-rc.9.9. 

Has anyone else observed this??

### PR DESCRIPTION
**Pull request by kaste**
For @pykong 

Follow up to #817 

Fixes #827

### CODE REVIEW

**Comment by kaste** [comment]
@braver Can I get a bit more permissions. I would like to add reviewers, assign myself on issues, probably close and tag issues.

**Comment by braver** [comment]
Definitely! Mi casa es su casa.

**Comment by pykong** [comment]
@kaste Does this PR replace #817 or supplement it?

**Comment by kaste** [comment]
This is a replacement

**Comment by braver** [comment]
@kaste what’s the status here? Shouldn’t #823 also cover this? Or does this need to be merged?

**Comment by kaste** [comment]
Usually FIFO order here for PRs?  This is blocked by the magic pykong PR bc otherwise he gets merge conflicts

**Comment by braver** [comment]
Yeah the leap frogging here is confusing me.

**Comment by kaste** [comment]
Rebased on master. 

PTAL @pykong @braver

**Pull request merged**
