### PR TITLE
Fix: Do not attempt to clear the cache for `create_environment`

### PR DESCRIPTION
**Pull request by kaste**
Bc it is not lru_cached'd anymore.

### CODE REVIEW

**Comment by braver** [comment]
LGTM

**Comment by kaste** [comment]
You review the really complicated stuff.

**Comment by kaste** [comment]
Maybe I should do the trivial stuff on master directly.

**Comment by braver** [comment]
> You review the really complicated stuff.

In 7 minutes flat ;). I did actually check this one. But I didn't give you access for you to ask permission for everything you know, just push if you're certain it's a good change. I have a really hard time keeping up with the changes this week already (a good problem to have!).

**Pull request merged**
