### PR TITLE
Iterate args DSL

### LINKED ISSUE #1286: Allow something like `--foo` in our args DSL
Generally, `defaults` has DSL abracadabra.

We support `--foo bar` via `"--foo:"` and `--foo=bar` via `--foo=`. Now, for the `=` case this is somewhat okay, but it would be nice if we could just specify `"--foo"` (without the `:`) in the first case.

### PR DESCRIPTION
**Pull request by kaste**
- Make \<joiner> optional
- Remove special '@' handling
- Use the value `True` as flag
- Simplify code by checking for falsy values first

Fixes #1286

### CODE REVIEW

**Comment by braver** [comment]
Oh boy. I know nothing about this. Does this break plugins?

**Comment by kaste** [comment]
Of course not. LOL

**Comment by braver** [comment]
image

**Comment by braver** [comment]
No, this is me reading the diff: 

confused math gif by cbc-downsized

**Comment by kaste** [comment]
So I guess you kinda figured it out

**Comment by kaste** [comment]
I'll merge this. This is a BREAKING CHANGE for the `True` case only

```
before:
	'--stdin': True  => '--stdin True'

after:
	'--stdin': True   => '--stdin'
	'--stdin': 'True' => '--stdin True'
```

Note that it was not possible before to just set the flag '--stdin' bc all falsy values meant skip this arg.

**Comment by kaste** [comment]
Notable: The joiner is now optional.

```
before:
	'--stdin:': True
            ^ ugly
after:
	'--stdin': True
```

**Pull request merged**
