### PR TITLE
Filter duplicate events

### LINKED ISSUE #1338: Factor decorators which filter unnecessary double view events
Most of the time Sublime fires the same event multiple times per view into the same buffer. We usually don't need that but have applied various patches throughout the code base.

For `on_post_save` and `on_modified` events we should only pass distinct (view.buffer.id(), view.change_count()) pairs. 

For `on_selection` we should pass distinct (view.buffer_id(), *view.sel()) tuples. 

Decorators are a good first implementation here. If we actually know what we need, a CommonController (t.i. we implement exactly *one* `sublime_plugin.EventListener`) that fires normalized events would be preferable.

### PR DESCRIPTION
**Pull request by kaste**
Closes #1338

### CODE REVIEW

**Comment by braver** [comment]
Eh, whoops? This is on restart with just a single file open.

```
Traceback (most recent call last):
  File "/Users/koenlageveen/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 594, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 70, in wrapper
    this_call = (view.buffer_id(),) + tuple(chain(*(s for s in view.sel())))
TypeError: 'Region' object is not iterable
Traceback (most recent call last):
  File "/Users/koenlageveen/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 594, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 70, in wrapper
    this_call = (view.buffer_id(),) + tuple(chain(*(s for s in view.sel())))
TypeError: 'Region' object is not iterable
Traceback (most recent call last):
  File "/Users/koenlageveen/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 594, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 70, in wrapper
    this_call = (view.buffer_id(),) + tuple(chain(*(s for s in view.sel())))
TypeError: 'Region' object is not iterable
Traceback (most recent call last):
  File "/Users/koenlageveen/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 594, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 70, in wrapper
    this_call = (view.buffer_id(),) + tuple(chain(*(s for s in view.sel())))
TypeError: 'Region' object is not iterable
Traceback (most recent call last):
  File "/Users/koenlageveen/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 594, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 70, in wrapper
    this_call = (view.buffer_id(),) + tuple(chain(*(s for s in view.sel())))
TypeError: 'Region' object is not iterable
Traceback (most recent call last):
  File "/Users/koenlageveen/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 594, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/util.py", line 70, in wrapper
    this_call = (view.buffer_id(),) + tuple(chain(*(s for s in view.sel())))
TypeError: 'Region' object is not iterable
```

**Comment by kaste** [comment]
Whoopsi Goldberg? You know what, I have the Prettier plugin installed which apparently monkeypatches (!) sublime.Region so that it becomes iterable and I don't have this error. Thank you for that.

**Comment by braver** [comment]
These days I actually review the python in plugins before I install them. Too much monkeying about.

**Comment by kaste** [comment]
C'mon `babel-sublime` applies the same hack. 🙄

**Pull request merged**
