### PR TITLE
Fix: Source gutter icons from all linters of current file

### LINKED ISSUE #1302: gutter icons "protected regions" don't always work
Perhaps since recent work on master. 

screen shot 2018-04-09 at 20 55 20

They do sometimes show, and it feels like a race condition somewhere.

Also, sometimes I can get the line report tooltip even if the icon is hidden by GitGutter, and sometimes I can't get the line report tooltip no matter what. The inline tooltip for regions is more reliable however.

tooltips

### PR DESCRIPTION
**Pull request by kaste**
Fixes #1302

### CODE REVIEW

**Comment by braver** [comment]
That doesn't fix the problem for me, I can still reproduce the gif from #1302

**Comment by kaste** [comment]
This one solves the second one. The animated.

**Comment by kaste** [comment]
Before 



After

**Comment by braver** [comment]
Ok that fixes at least one problem then, I got to find out what my problem is then. It’s nothing to do with gitgutter, but the data internally is incorrect.

**Comment by kaste** [comment]
The bug here was easy to reproduce and easy to see in the code. It was clear that the var `errors_for_the_gutter` first holds *all* gutter icons and a few lines later holds only the gutter icons from the latest arriving linter. And I took the wrong one.

**Comment by braver** [comment]
Excellent, works now!

⛵️

**Pull request merged**
