### PR TITLE
Support lint_mode option for specific linters

### PR DESCRIPTION
**Pull request by bongnv**
This is an attempt PR to close this task #244 . In this PR, I add method `should_lint` in the base linter to support:
- decides whether the linter should start or not based on a given reason
- check `lint_mode` with `reason` to decide whether it should check the given view or not
- allows each custom Linter to programmatically decide whether it should take action on each trigger or not
Docs also is added but not sure if it has the correct format. Please help to verify.

### CODE REVIEW

**Comment by kaste** [comment]
Very cool! Thank you. 

As you can see I already prepared implementing that feature with the `reason` arg we can pass around. Now, the idea was to finally decide if we actually *will* lint at this time in `skip_linter` within `sublime_linter.py`. 

I think, we cannot use `get_linters_for_view` which then asks `can_lint_view` bc `get_linters_for_view` has enormous side-effects (You may have read the comment there "Yeah, it's a *getter* LOL.") and if it doesn't return a stable set of linters we erase all collected lint errors all the time. Also the status bar indicating which linter has been assign to the view (e.g. showing 'eslint(ok)') would probably flicker, change all the time.

Within `skip_linter(linter, view) -> bool` you can get the settings using the function `get_linter_settings(linter, view)` from `linter.py`.

**Comment by bongnv** [comment]
Hi @kaste,
Thanks for reviewing. I've updated the PR. Basically, it renames func `skip_linter` to `should_lint` and move it base linter implementation. By doing this, it allows each custom linter to programmatically decide whether it should lint the attached view based on a trigger or not.

**Comment by kaste** [comment]
That's perfect. :+1:

**Comment by kaste** [comment]
Thanks again. 

Do you want to further iterate on this topic? Your PR allows 'demoting' the globally `lint_mode`. T.i. if the user is in background-mode globally, he can now declare a specific linter to be 'only' in 'on_save' mode. But not vice-versa. 

So, the next iteration would be that a specific 'lint_mode' setting will overrule (take precedence) over the global user settings. 

The idea I had is to just remove the prechecks in the `BackendController` in `sublime_linter.py`, and then take the global 'lint_mode' in `should_lint` as a fallback.

WDYT?

**Comment by kaste** [comment]
Related #1230

We want to change lint_mode to only (background|save|manual). This matches the reasons (None|on_save|on_user_request) and in turn the events (on_modified|on_save|LintViewCommand).

We introduce a new setting lint_on_load(true|false) which we check in the event handler on_activated which will then in turn hit with the reason on_user_request. 

So the complete feature set is in the end a breaking change.

This is just to give a broader perspective. Take whatever you want and ask questions if you have any.

**Comment by braver** [comment]
@bongnv we got some donations recently and I would like to share some of it with you. Do you have a PayPal address?

**Comment by bongnv** [comment]
Hi,
I appreciate that. I'm just good. Please give it to who need. Thanks.
Bong

**Comment by braver** [comment]
👍🏻

**Pull request merged**
