### PR TITLE
Unit tests [WIP]

### PR DESCRIPTION
**Pull request by kaste**
Yes, unit tests

### CODE REVIEW

**Comment by kaste** [comment]
image

It's only adding=documenting the current behavior.

**Comment by braver** [comment]
Cool! The trouble is always in maintaining these things when you’re making sweeping changes, so now would be a good time to introduce these tests. Any particular reason you picked mockito?

**Comment by kaste** [comment]
>  Any particular reason you picked mockito?

Well, I'm the maintainer. (Ideally I would go with pytest + mockito.)

**Comment by braver** [comment]
Nifty

**Comment by kaste** [comment]
🍄

**Pull request merged**
